routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/products', 'ProductController');

app/Product.php
<?php

namespace App;

use App\ProductStock;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function productStocks () {
    	return $this->hasMany('App\ProductStock');
    }

    public function user () {
    	return $this->belongsTo('App\User', 'created_by');
    }

    public function totalCount()
    {
    	return ProductStock::where('is_active', 1)->where('product_id', $this->id)->sum('count');
    }

    public function sumPrice()
    {
    	return ProductStock::where('is_active', 1)->where('product_id', $this->id)->sum('unit_price') / 100;
    }
    
    
}

app/ProductStock.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductStock extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\ProductStock;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $products = [];

        $type = $request['type'] ?? 1;

        $productList = Product::where('is_active', 1)->get(['id', 'name', 'is_active', 'created_by']);

        foreach($productList as $p) {
            $qualified = 0;
            $totalCount = $p->totalCount();

            if($type == 1 || is_null($type)) {
                if($totalCount > 0) $qualified = 1;
            }
            else if ($type == 0) {
                if($totalCount == 0) $qualified = 1;
            }
            else {
                $qualified = 1;
            }

            if($qualified) {
                $products[] = [
                    'id' => $p->id,
                    'name' => $p->name,
                    'is_active' => $p->is_active,
                    'created_by' => $p->user->name,
                    'totalProduct' => $totalCount,
                    'sumPrice' => $p->sumPrice()
                ];
            }
            
        }

        return response()->json($products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('add-product', compact(['product']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'count' => 'numeric|min:1',
            'unit_price' => 'numeric|min:.5',
        ]);

        $productStock = new ProductStock;

        $productStock->count = $request->input('count');
        $productStock->unit_price = $request->input('unit_price') * 100;
        $productStock->is_active = $request->input('is_active');
        
        $newStock = $product->productStocks()->save($productStock);

        if($newStock) {
            session()->flash('type', 'success');
            session()->flash('status', 'Product Added Successfully');

            // return redirect()->route('products.index');
            return redirect()->route('home');
        }

        return back();
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/add-product.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id="productList">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Add Product</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    
                    <form action="{{ route('products.update', ['product' => $product->id]) }}" method="post">
                      @csrf
                      @method('PATCH')
                      
                      <div class="form-group">
                        <label for="email">Product Name:</label>
                        <strong>{{ $product->name }}</strong>
                      </div>

                      <div class="form-group">
                        <label for="count">Count/ Quantity:</label>
                        <input type="text" class="form-control" id="count" name="count">
                      </div>

                      <div class="form-group">
                        <label for="unit_price">Unit Price:</label>
                        <input type="text" class="form-control" id="unit_price" name="unit_price">
                      </div>

                      <div class="checkbox">
                        <label><input type="checkbox" name="is_active" value="1" checked> Active</label>
                      </div>

                      <button type="submit" class="btn btn-success">Save</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('footerScript')
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id="productList">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <h3>Product List (<a @click="loadProducts(1)">Active</a> | <a @click="loadProducts(2)">All</a> | <a @click="loadProducts(0)">Null</a>)</h3>
                    <table class="table">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Name</th>
                          <th scope="col">Count</th>
                          <th scope="col" class="text-right">Sum Price</th>
                          <th scope="col">Status</th>
                          <th scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody v-if="products.length">
                        <tr v-for="product in products" :key="product.id">
                          <th scope="row">@{{ product.id }}</th>
                          <td>@{{ product.name }}</td>
                          <td>@{{ product.totalProduct }}</td>
                          <td class="text-right">$ @{{ product.sumPrice }}</td>
                          <td>@{{ statuses[product.is_active] }}</td>
                          <td>
                            <a :href="'/products/' + product.id + '/edit'" class="btn btn-success btn-sm">Add</a>
                          </td>
                        </tr>
                      </tbody>
                      <tbody v-else>
                        <tr>
                          <td colspan="6">No Record Found !!</td>
                        </tr>
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('footerScript')
    <script src="{{ asset('jquery.min.js') }}"></script>
    <script src="{{ asset('axios.min.js') }}"></script>
    <script src="{{ asset('vue.js') }}"></script>
    <script>
        var vm = new Vue({
            el: '#productList',
            data: {
                products: [],
                statuses: [
                  'Inactive',
                  'Active',
                ],
            },
            methods: {
                loadProducts: function(type) {
                    var app = this;
                    app.products = [];

                    axios.get('{{ route("products.index") }}?type=' + type)
                      .then(function (response) {
                        // handle success
                        /* 
                        response.data.map(function(product) {
                           console.log(product)
                            app.products.push(product);
                        }) 
                        */

                        app.products = response.data;

                        // console.log(app.products.length)
                      })
                      .catch(function (error) {
                        // handle error
                        // console.log(error);
                      });
                }
            },
            mounted: function() {
                var app = this;
                app.loadProducts('');

                $('#myModal').on('shown.bs.modal', function () {
                  $('#myInput').trigger('focus')
                })
            }
        })
    </script>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('bootstrap.min.css') }}">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <!-- jQuery library -->
    <script src="{{ asset('jquery.min.js') }}"></script>
    <!-- Latest compiled JavaScript -->
    <script src="{{ asset('bootstrap.min.js') }}">

    @yield('footerScript')
</body>
</html>